import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, GenerateVideosOperation } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;

// Increase request limit for handling base64 uploads
app.use(express.json({ limit: '60mb' }));
app.use(express.urlencoded({ limit: '60mb', extended: true }));

// Initialize Gemini SDK with telemetry header
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    }
  }
});

// 1. High-quality Image Generation API using gemini-3-pro-image-preview
app.post("/api/generate-image", async (req, res) => {
  try {
    const { prompt, size = "1K", aspectRatio = "1:1" } = req.body;
    if (!prompt) {
      return res.status(400).json({ error: "Prompt is required" });
    }

    console.log(`Generating image. Prompt: "${prompt}", Size: ${size}, Aspect Ratio: ${aspectRatio}`);

    const response = await ai.models.generateContent({
      model: 'gemini-3-pro-image-preview',
      contents: prompt,
      config: {
        imageConfig: {
          aspectRatio,
          imageSize: size
        }
      }
    });

    let base64 = "";
    const parts = response.candidates?.[0]?.content?.parts || [];
    for (const part of parts) {
      if (part.inlineData && part.inlineData.data) {
        base64 = part.inlineData.data;
        break;
      }
    }

    if (!base64) {
      return res.status(500).json({ error: "No image data was generated by the model" });
    }

    res.json({
      success: true,
      base64,
      mimeType: "image/png"
    });
  } catch (error: any) {
    console.error("Image generation failed:", error);
    res.status(500).json({ error: error.message || "Failed to generate image" });
  }
});

// 2. Smart Assistant / Route Planner with Maps Grounding using gemini-3.5-flash + googleMaps tool
app.post("/api/maps-grounding", async (req, res) => {
  try {
    const { prompt } = req.body;
    if (!prompt) {
      return res.status(400).json({ error: "Prompt is required" });
    }

    console.log(`Processing Maps Grounding query: "${prompt}"`);

    const response = await ai.models.generateContent({
      model: 'gemini-3.5-flash',
      contents: prompt,
      config: {
        systemInstruction: "Вы — интерактивный гид-ассистент DU-SUP по реке Агидель, Дюртюлям и окрестностям Башкортостана. Отвечайте вежливо, на русском языке. Всегда используйте инструмент Google Maps для поиска актуальной информации о географических точках, достопримечательностях, ресторанах, базах отдыха или погоде в районе Дюртюлей.",
        tools: [{ googleMaps: {} }]
      }
    });

    res.json({
      success: true,
      text: response.text,
      groundingMetadata: response.candidates?.[0]?.groundingMetadata
    });
  } catch (error: any) {
    console.error("Maps grounding query failed:", error);
    res.status(500).json({ error: error.message || "Failed to process query with Google Maps data" });
  }
});

// 3. Start Image to Video Generation (Veo) using veo-3.1-fast-generate-preview
app.post("/api/generate-video", async (req, res) => {
  try {
    const { prompt, imageBytes, mimeType = "image/png", aspectRatio = "16:9" } = req.body;
    if (!imageBytes) {
      return res.status(400).json({ error: "A starting image (base64) is required for video animation" });
    }

    console.log(`Starting Veo video generation. Prompt: "${prompt || 'Animatating photo'}", Aspect Ratio: ${aspectRatio}`);

    const payload: any = {
      model: 'veo-3.1-fast-generate-preview',
      image: {
        imageBytes,
        mimeType,
      },
      config: {
        numberOfVideos: 1,
        resolution: '720p',
        aspectRatio
      }
    };

    if (prompt) {
      payload.prompt = prompt;
    }

    const operation = await ai.models.generateVideos(payload);
    console.log(`Started operation: ${operation.name}`);

    res.json({
      success: true,
      operationName: operation.name
    });
  } catch (error: any) {
    console.error("Veo video generation failed:", error);
    res.status(500).json({ error: error.message || "Failed to start video generation" });
  }
});

// 4. Poll status of video generation operation
app.post("/api/video-status", async (req, res) => {
  try {
    const { operationName } = req.body;
    if (!operationName) {
      return res.status(400).json({ error: "operationName is required" });
    }

    const op = new GenerateVideosOperation();
    op.name = operationName;

    const updated = await ai.operations.getVideosOperation({ operation: op });
    res.json({
      success: true,
      done: updated.done
    });
  } catch (error: any) {
    console.error("Video status polling failed:", error);
    res.status(500).json({ error: error.message || "Failed to poll video status" });
  }
});

// 5. Download the completed video file
app.post("/api/video-download", async (req, res) => {
  try {
    const { operationName } = req.body;
    if (!operationName) {
      return res.status(400).json({ error: "operationName is required" });
    }

    console.log(`Downloading video for operation: ${operationName}`);

    const op = new GenerateVideosOperation();
    op.name = operationName;

    const updated = await ai.operations.getVideosOperation({ operation: op });
    const uri = updated.response?.generatedVideos?.[0]?.video?.uri;

    if (!uri) {
      return res.status(404).json({ error: "Video URI not found on completed operation" });
    }

    const videoRes = await fetch(uri, {
      headers: { 'x-goog-api-key': process.env.GEMINI_API_KEY || '' },
    });

    if (!videoRes.ok) {
      return res.status(videoRes.status).json({ error: "Failed to download video from upstream" });
    }

    res.setHeader('Content-Type', 'video/mp4');
    const arrayBuffer = await videoRes.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);
    res.send(buffer);
  } catch (error: any) {
    console.error("Video download failed:", error);
    res.status(500).json({ error: error.message || "Failed to download video" });
  }
});

// Start server and handle Vite asset rendering / SPA serving
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
